import { ensureSeed, getSettings, saveSettings, getCollection, saveItem, deleteItem } from './data.js';

const tabs = [
  ['dashboard','Dashboard'],['settings','Store'],['categories','Categories'],['products','Products'],['notification','Notice & Promo'],['orders','Orders'],['future','Future']
];
const state = { settings:null, categories:[], products:[], promos:[], orders:[], active:'dashboard' };
const $ = sel => document.querySelector(sel);
const $$ = sel => Array.from(document.querySelectorAll(sel));
const money = n => '₹' + Number(n||0).toFixed(0);
function toast(msg){ alert(msg); }

function switchTab(name){ state.active = name; tabs.forEach(([id])=>{ $(`#tab-${id}`).classList.toggle('hidden', id!==name); }); $$('.tab-btn').forEach(btn=>btn.classList.toggle('active', btn.dataset.tab===name)); if(name==='dashboard') renderDashboard(); }
function renderTabs(){ $('#adminTabs').innerHTML = tabs.map(([id,label])=>`<button class="tab-btn ${id===state.active?'active':''}" data-tab="${id}">${label}</button>`).join(''); $$('.tab-btn').forEach(btn=>btn.onclick=()=>switchTab(btn.dataset.tab)); }
function renderDashboard(){ const el = $('#tab-dashboard'); const totalSales = state.orders.reduce((s,o)=>s+Number(o.total||0),0); el.innerHTML = `<div class="kpi-grid"><div class="kpi"><div class="small muted">Total Orders</div><div class="num">${state.orders.length}</div></div><div class="kpi"><div class="small muted">Products</div><div class="num">${state.products.length}</div></div><div class="kpi"><div class="small muted">Categories</div><div class="num">${state.categories.length}</div></div><div class="kpi"><div class="small muted">Sales</div><div class="num">${money(totalSales)}</div></div></div>`; }
function fillSettings(){ const s = state.settings; $('#s_storeName').value=s.storeName||''; $('#s_heroTitle').value=s.heroTitle||''; $('#s_heroSub').value=s.heroSub||''; $('#s_logoUrl').value=s.logoUrl||''; $('#s_supportPhone').value=s.supportPhone||''; $('#s_whatsappNumber').value=s.whatsappNumber||''; $('#s_minOrderValue').value=s.minOrderValue||500; $('#s_topNotice').value=s.offerMarquee||''; $('#s_notificationEnabled').checked=!!s.notificationEnabled; $('#s_notificationText').value=s.notificationText||''; $('#s_helpText').value=s.helpText||''; }
function renderCategoryOptions(){ $('#p_category').innerHTML = state.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); }
function renderCategories(){ const list = $('#categoriesList'); list.innerHTML = state.categories.sort((a,b)=>(a.order||0)-(b.order||0)).map(c=>`<div class="item"><div class="between"><div><div style="font-weight:700">${c.name}</div><div class="small muted">${c.supportType||'none'} • ${c.supportValue||'-'}</div></div><button class="btn danger" style="width:auto;padding:8px 12px" data-del="${c.id}">Delete</button></div></div>`).join(''); list.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=async()=>{ await deleteItem('categories', btn.dataset.del); await load(); switchTab('categories'); }); }
function renderProducts(){ const list = $('#productsList'); list.innerHTML = state.products.map(p=>`<div class="item"><div class="between"><div><div style="font-weight:700">${p.name}</div><div class="small muted">${categoryName(p.categoryId)} • ${money(p.price)} ${p.stock?'• In stock':'• Out of stock'}</div></div><button class="btn danger" style="width:auto;padding:8px 12px" data-del="${p.id}">Delete</button></div></div>`).join(''); list.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=async()=>{ await deleteItem('products', btn.dataset.del); await load(); switchTab('products'); }); }
function renderPromos(){ const list = $('#promosList'); list.innerHTML = state.promos.sort((a,b)=>(a.order||0)-(b.order||0)).map(p=>`<div class="item"><div class="between"><div><div style="font-weight:700">${p.title||p.type}</div><div class="small muted">${p.type} • order ${p.order||0}</div></div><button class="btn danger" style="width:auto;padding:8px 12px" data-del="${p.id}">Delete</button></div></div>`).join(''); list.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=async()=>{ await deleteItem('promos', btn.dataset.del); await load(); switchTab('notification'); }); }
function renderOrders(){ const list = $('#ordersList'); if(!state.orders.length){ list.innerHTML='<div class="card small muted">Abhi koi order nahi aaya.</div>'; return; } list.innerHTML = state.orders.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(o=>`<div class="item"><div style="font-weight:700">${o.profile?.name||'Customer'} • ${money(o.total)}</div><div class="small muted">${o.profile?.phone||''} • ${o.profile?.address||''}</div><div class="small muted">${(o.items||[]).map(i=>`${i.name} × ${i.qty}`).join(', ')}</div></div>`).join(''); }
function categoryName(id){ return state.categories.find(c=>c.id===id)?.name || 'Unknown'; }
function fillFuture(){ const f = state.settings.integrations || {}; $('#f_riderEnabled').checked=!!f.riderEnabled; $('#f_riderAppName').value=f.riderAppName||''; $('#f_riderAppLink').value=f.riderAppLink||''; $('#f_billingEnabled').checked=!!f.billingEnabled; $('#f_billingAppName').value=f.billingAppName||''; $('#f_billingAppLink').value=f.billingAppLink||''; $('#f_receiptEnabled').checked=!!f.receiptEnabled; $('#f_receiptPrefix').value=f.receiptPrefix||''; $('#f_receiptTemplate').value=f.receiptTemplate||''; }

async function load(){ await ensureSeed(); state.settings = await getSettings(); state.categories = await getCollection('categories'); state.products = await getCollection('products'); state.promos = await getCollection('promos'); state.orders = await getCollection('orders'); renderTabs(); renderDashboard(); fillSettings(); renderCategoryOptions(); renderCategories(); renderProducts(); renderPromos(); renderOrders(); fillFuture(); $('#n_text').value = state.settings.notificationText || ''; $('#n_enabled').checked = !!state.settings.notificationEnabled; }

function bind(){
  $('#saveSettingsBtn').onclick = async()=>{ state.settings = { ...state.settings, storeName:$('#s_storeName').value.trim(), heroTitle:$('#s_heroTitle').value.trim(), heroSub:$('#s_heroSub').value.trim(), logoUrl:$('#s_logoUrl').value.trim()||'logo.svg', supportPhone:$('#s_supportPhone').value.trim(), whatsappNumber:$('#s_whatsappNumber').value.trim(), minOrderValue:Number($('#s_minOrderValue').value||500), offerMarquee:$('#s_topNotice').value.trim(), notificationEnabled:$('#s_notificationEnabled').checked, notificationText:$('#s_notificationText').value.trim(), helpText:$('#s_helpText').value.trim() }; await saveSettings(state.settings); toast('Settings saved'); await load(); };
  $('#saveCategoryBtn').onclick = async()=>{ const name = $('#c_name').value.trim(); if(!name) return toast('Category name dalo'); await saveItem('categories', { id: slug(name), name, image:$('#c_image').value.trim(), order:Number($('#c_order').value||state.categories.length+1), supportType:$('#c_supportType').value, supportValue:$('#c_supportValue').value.trim(), active:true }); ['#c_name','#c_image','#c_order','#c_supportValue'].forEach(s=>$(s).value=''); await load(); switchTab('categories'); };
  $('#saveProductBtn').onclick = async()=>{ const name = $('#p_name').value.trim(); if(!name) return toast('Product name dalo'); await saveItem('products', { name, brand:$('#p_brand').value.trim(), size:$('#p_size').value.trim(), image:$('#p_image').value.trim(), price:Number($('#p_price').value||0), mrp:Number($('#p_mrp').value||0), categoryId:$('#p_category').value, stock:$('#p_stock').checked }); ['#p_name','#p_brand','#p_size','#p_image','#p_price','#p_mrp'].forEach(s=>$(s).value=''); $('#p_stock').checked=true; await load(); switchTab('products'); };
  $('#saveNotificationBtn').onclick = async()=>{ state.settings = { ...state.settings, notificationText:$('#n_text').value.trim(), notificationEnabled:$('#n_enabled').checked }; await saveSettings(state.settings); toast('Notification saved'); await load(); };
  $('#savePromoBtn').onclick = async()=>{ const url = $('#promo_url').value.trim(); if(!url) return toast('Promo URL dalo'); await saveItem('promos', { type:$('#promo_type').value, url, title:$('#promo_title').value.trim(), subtitle:$('#promo_subtitle').value.trim(), order:Number($('#promo_order').value||state.promos.length+1), enabled:$('#promo_enabled').checked }); ['#promo_url','#promo_title','#promo_subtitle','#promo_order'].forEach(s=>$(s).value=''); $('#promo_type').value='image'; $('#promo_enabled').checked=true; await load(); switchTab('notification'); };
  $('#saveFutureBtn').onclick = async()=>{ state.settings.integrations = { riderEnabled:$('#f_riderEnabled').checked, riderAppName:$('#f_riderAppName').value.trim(), riderAppLink:$('#f_riderAppLink').value.trim(), billingEnabled:$('#f_billingEnabled').checked, billingAppName:$('#f_billingAppName').value.trim(), billingAppLink:$('#f_billingAppLink').value.trim(), receiptEnabled:$('#f_receiptEnabled').checked, receiptPrefix:$('#f_receiptPrefix').value.trim(), receiptTemplate:$('#f_receiptTemplate').value.trim() }; await saveSettings(state.settings); toast('Future structure saved'); await load(); };
}
function slug(text){ return String(text||'').toLowerCase().replace(/[^a-z0-9]+/g,'-'); }

bind();
load();
